pull_request_rules: []
merge_protections:
  - name: VM6 Fixture Always Green
    if:
      - base = main
    success_conditions:
      - base = main
merge_protections_settings:
  reporting_method: check-runs
  post_comment: true
  auto_merge_conditions: true
